image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - docker pull $IMAGE_TAG:builder-latest || true
    ## builder image for caching:
    ## https://github.com/moby/moby/issues/34715
    ## https://gitlab.com/gitlab-org/gitlab-omnibus-builder/merge_requests/83
    - docker build --pull
                   --cache-from $IMAGE_TAG:builder-latest
                   --tag $IMAGE_TAG:builder-latest
                   --target builder 
                   .
    ## 2nd stage build using builder-latest for caching
    - docker build --pull
                   --cache-from $IMAGE_TAG:builder-latest
                   --tag $IMAGE_TAG:test
                   .
    - docker push $IMAGE_TAG:builder-latest
    - docker push $IMAGE_TAG:test
  retry: 2

test01:
  stage: test
  script:
    - docker pull $IMAGE_TAG:test
    - docker run --rm
                 -v $(pwd)/demos:/tmp/demos
                 --workdir /tmp/demos/
                 $IMAGE_TAG:test
                 FacetAnalyserCLI  8faced-rhombic-dodecahedron_twinned_010_deformed_wss.vtp 51 15 0.2 0.001 2 8faced-rhombic-dodecahedron_twinned_010_deformed_wss_FA.vtp

